#!/bin/bash
echo "Criando usuários via CLI do Medusa..."
echo ""
echo "Para Gabriel:"
echo "1. Execute: yarn medusa user"
echo "2. Email: gabriel@xodozin.com.br"
echo "3. Senha: Gabriel123!"
echo "4. Confirme a senha: Gabriel123!"
echo ""
echo "Para Anne:"
echo "1. Execute: yarn medusa user"
echo "2. Email: anne@xodozin.com.br"
echo "3. Senha: Anne123!"
echo "4. Confirme a senha: Anne123!"
echo ""
echo "⚠️  O CLI precisa ser executado interativamente (não pode ser automatizado)"
